# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go run main.go"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["vendor", "tmp", "node_modules"]
  exclude_file = []
  follow_symlink = true
  delay = 1000 # ms

[log]
  time = true

[color]
  main = "yellow"

[include]
  ext = ["go", "html"]
  path = ["pages", "partials", "."]
